server:
  port: 4446


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/warehouse_accounting
#    username: postgres
#    password: 8991

        url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/warehouse_accounting}
        username: ${SPRING_DATASOURCE_USERNAME:postgres}
        password: ${SPRING_DATASOURCE_PASSWORD:8991}

        java:
          runtime:
            version: 11

    initialization-mode: always
    data: classpath:sql_for_initializer/*.sql

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        format_sql: false
        jdbc:
          timezone: UTC

data-init:
  unit-data: src/main/resources/data_for_initializer/Валюта.xlsx